StoreDir = "/home/hadoop/data"

MasterHost = "localhost"
MasterPort = 8888

MetaType = "ClickHouse"

# Cassandra
CassandraHosts = ["localhost"]
Keyspace = "master"

# ClickHouse
ClickHouseHost = "tcp://127.0.0.1:9000?debug=true"

# redis
RedisHost = "localhost"
RedisPort = 6379
#Password = "110120"
Database = 0

# MAX Default volume number
MaxVolumeNum = 5

# cache
# doc: https://github.com/dgraph-io/ristretto
# number of keys to track frequency of (10M).
NumCounters = 10000000
# maximum cost of cache (1GB).
MaxCost = 1073741824
# number of keys per Get buffer.
BufferItem = 64
