MasterHost = "localhost"
MasterPort = 8888
MetaType = "Cassandra"
CassandraHosts = ["localhost"]
HbaseHost = "localhost"
ExpireMc = "10m"
MaxVolumeNum = 5

[Mc]
name = "xiaoyaofs"
proto = "tcp"
addr = "localhost:11211"
idle = 5
active = 10
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "80s"