StoreDir = "/Users/alex/go/src/github.com/AlexanderChiuluvB/xiaoyaoFS/storeDir1"
MountDir = "/Users/alex/mountTest1"
StoreApiHost = "localhost"
StoreApiPort = 7900

CassandraHosts = ["localhost"]
Keyspace = "store1"

ExpireMc = "10m"
[Mc]
name = "store1"
proto = "tcp"
addr = "localhost:11212"
idle = 5
active = 10
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "80s"