StoreDir = "/Users/alex/go/src/github.com/AlexanderChiuluvB/xiaoyaoFS/storeDir2"
StoreApiHost = "localhost"
StoreApiPort = 7901

ClickHouseHost = "tcp://127.0.0.1:9000?debug=true"

CassandraHosts = ["localhost"]
Keyspace = "store2"

ExpireMc = "10m"
[Mc]
name = "store2"
proto = "tcp"
addr = "localhost:11213"
idle = 5
active = 10
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "80s"