StoreDir = "/Users/alex/go/src/github.com/AlexanderChiuluvB/xiaoyaoFS/storeDir2"

StoreApiHost = "localhost"
StoreApiPort = 7901

MasterHost = "localhost"
MasterPort = 8888

HbaseHost = "localhost"

MetaType = "Cassandra"

CassandraHosts = ["localhost"]