StoreDir = "~/Desktop/Damon/storage"

StoreApiHost = "localhost"
StoreApiPort = 7900
MasterHost = "localhost"
MasterPort = 8888

MountDir = "~/Desktop/Damon/mount"

ClickHouseHost = "tcp://127.0.0.1:9000?debug=true"

CassandraHosts = ["localhost"]
Keyspace = "store1"

# LevelDB
# doc:
# 8MB
BlockCacheCapacity = 16388608
# 4MB
WriteBuffer = 8194304
CompactionTableSizeMultiplier = 4.0

NumCounters = 10000000
# maximum cost of cache (1GB).
MaxCost = 1073741824
# number of keys per Get buffer.
BufferItem = 64

