StoreDir = "/Users/alex/go/src/github.com/AlexanderChiuluvB/xiaoyaoFS/storeDir1"
MountDir = "/Users/alex/mountTest1"
StoreApiHost = "localhost"
StoreApiPort = 7900

MasterHost = "localhost"
MasterPort = 8888

HbaseHost = "localhost"

MetaType = "Cassandra"

CassandraHosts = ["localhost"]

ExpireMc = "10m"

[Mc]
name = "xiaoyaofs"
proto = "tcp"
addr = "localhost:11211"
idle = 5
active = 10
dialTimeout = "1s"
readTimeout = "1s"
writeTimeout = "1s"
idleTimeout = "80s"