StoreDir = "/Users/alex/go/src/github.com/AlexanderChiuluvB/xiaoyaoFS/storeDir1"
MountDir = "/Users/alex/mountTest1"
MasterHost = "localhost"
MasterPort = 8888
StoreApiHost = "localhost"
StoreApiPort = 7900
