StoreDir = "/Users/alex/go/src/github.com/AlexanderChiuluvB/xiaoyaoFS/storeDir"

StoreAdminHost = "localhost"
StoreAdminPort = 7800
StoreApiHost = "localhost"
StoreApiPort = 7900

MasterHost = "localhost"
MasterPort = 8888